
export const CASES_LOADING='CASES_LOADING';
export const CASES_FAILED='CASES_FAILED';
export const ADD_CASES='ADD_CASES';

export const TESTS_LOADING='TESTS_LOADING';
export const TESTS_FAILED='TESTS_FAILED';
export const ADD_TESTS='ADD_TESTS';

